#!/usr/bin/python3

import re

DATA_PATH = "./data/2015/day_03.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def part_1(content):
    list = re.findall(r"mul\([0-9]{1,3},[0-9]{1,3}\)", content)
    result = 0
    for expression in list:
        numbers = re.findall(r"[0-9]+", expression)
        try :
            nb1 = int(numbers[0])
            nb2 = int(numbers[1])
            result += nb1 * nb2
        except:
            pass
    return result

def part_2(content):
    list = re.findall(r"mul\([0-9]{1,3},[0-9]{1,3}\)|do\(\)|don't\(\)", content)
    enable = True
    result = 0
    for expression in list:
        if (expression == "do()") :
            enable = True
        elif (expression == "don't()"):
            enable = False
        if not enable:
            continue
        numbers = re.findall(r"[0-9]+", expression)
        try :
            nb1 = int(numbers[0])
            nb2 = int(numbers[1])
            result += nb1 * nb2
        except:
            pass
    return result

if __name__ == "__main__":
    content = get_file_content(DATA_PATH)
    print(f"Part 1: {part_1(content)}")
    print(f"Part 2: {part_2(content)}")
