#!/usr/bin/python3

import re
DATA_PATH = "./data/2015/day_08.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def part_1(content):
    code = 0
    memory = 0

    for line in content:
        code += len(line)
        new_str = line[1:-1]
        new_str = re.sub(r"\\x[a-fA-F0-9]{2}", "x", new_str)
        new_str = re.sub(r"\\\"", "\"", new_str)
        new_str = re.sub(r"\\\\", r"\\", new_str)
        memory += len(new_str)
    return code - memory

def part_2(content):
    code = 0
    encoded = 0

    for line in content:
        code += len(line)
        matches = re.finditer(r"\"|\\", line)
        indices = [match.start() for match in matches]
        new_str = line[:]
        for i in range(len(indices) - 1, -1, -1):
            pos = indices[i]
            new_str = new_str[:pos] + '\\' + new_str[pos:]
        new_str = '"' + new_str + '"'
        encoded += len(new_str)
    return encoded - code

if __name__ == "__main__":
    content = get_file_content(DATA_PATH)
    content = content.split("\n")
    print(f"Part 1: {part_1(content)}")
    print(f"Part 2: {part_2(content)}")
