#!/usr/bin/python3

DATA_PATH = "./data/2015/day_01.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def part_1(content):
    floor = 0
    for char in content:
        floor += 1 if char == '(' else -1 if char == ')' else 0
    return floor

def part_2(content):
    floor = 0
    index = 1
    for char in content:
        floor += 1 if char == '(' else -1 if char == ')' else 0
        if floor <= -1:
            return index
        index += 1
    return index

if __name__ == "__main__":
    content = get_file_content(DATA_PATH)
    print(f"Part 1: {part_1(content)}")
    print(f"Part 2: {part_2(content)}")
