#!/usr/bin/python3

import re
import json

DATA_PATH = "./data/2015/day_12.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def extract_numbers(json_text):
    matches = re.findall(r"-?\d+", json_text)
    return [int(m) for m in matches]

def part_1(content):
    return sum(extract_numbers(content))

def parseObject(obj):
    if isinstance(obj, dict):
        if "red" in obj.values():
            return 0
        return sum(map(parseObject, obj.values()))
    elif isinstance(obj, list):
        return sum(map(parseObject, obj))
    elif isinstance(obj, int):
        return obj
    else:
        return 0

def part_2(content):
    return parseObject(json.loads(content))

if __name__ == "__main__":
    content = get_file_content(DATA_PATH)
    print(f"Part 1: {part_1(content)}")
    print(f"Part 2: {part_2(content)}")
