#!/usr/bin/python3

import re

DATA_PATH = "./data/2015/day_16.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

mfcam = {
    "children": 3,
    "cats": 7,
    "samoyeds": 2,
    "pomeranians": 3,
    "akitas": 0,
    "vizslas": 0,
    "goldfish": 5,
    "trees": 3,
    "cars": 2,
    "perfumes": 1
}

def parseLine(line):
    pattern = re.compile(r"Sue (\d+): ([a-z]+): (\d+), ([a-z]+): (\d+), ([a-z]+): (\d+)")

    aunt = {}
    match = pattern.match(line)
    if match:
        i = 2
        aunt["name"] = int(match.group(1))
        for _ in range(3):
            aunt[match.group(i)] = int(match.group(i + 1))
            i += 2
    return aunt

def getAuntScore1(aunt):
    score = 0
    for k in mfcam:
        if k not in aunt:
            continue
        if aunt[k] == mfcam[k]:
            score += 1
    return score

def getAuntScore2(aunt):
    score = 0
    for k in mfcam:
        if k not in aunt:
            continue
        if k == "trees" or k == "cats":
            if aunt[k] > mfcam[k]:
                score += 1
        elif k == "pomeranians" or k == "goldfish":
            if aunt[k] < mfcam[k]:
                score += 1
        elif aunt[k] == mfcam[k]:
            score += 1
    return score

def findAuntSue(content, getAuntScore):
    maxScore = -1
    index = -1
    for line in content:
        aunt = parseLine(line)
        score = getAuntScore(aunt)
        if score > maxScore:
            index = aunt["name"]
            maxScore = score
    return index

def part_2(content):
    pass

if __name__ == "__main__":
    content = [row for row in get_file_content(DATA_PATH).split("\n") if row]
    print(f"Part 1: {findAuntSue(content, getAuntScore1)}")
    print(f"Part 2: {findAuntSue(content, getAuntScore2)}")
