#!/usr/bin/python3

DATA_PATH = "./data/2015/day_18.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def getNeighbors(map, i, j):
    count = 0
    for x in range(-1, 2):
        for y in range(-1, 2):
            if (x == 0 and y == 0) or i + x < 0 or i + x >= len(map) or j + y < 0 or j + y >= len(map[0]):
                continue
            if map[i + x][j + y] == "#":
                count += 1
    return count

def countOnLight(map):
    count = 0
    for i in range(len(map)):
        for j in range(len(map[i])):
            if map[i][j] == '#':
                count += 1
    return count

def GameOfLife(map, timer, postProcessMap = None):
    for _ in range(timer):
        dup_map = [row[:] for row in map]
        for i in range(len(map)):
            for j in range(len(map[i])):
                count = getNeighbors(map, i, j)
                if map[i][j] == '#' and (count >= 2 and count <= 3):
                    dup_map[i][j] = '#'
                elif map[i][j] == '.' and count == 3:
                    dup_map[i][j] = '#'
                else:
                    dup_map[i][j] = '.'
        map = [row[:] for row in dup_map]
        if postProcessMap:
            map = postProcessMap(map)
    return countOnLight(map)

def turnCornerOn(map):
    map[0][0] = '#'
    map[0][len(map[0]) - 1] = '#'
    map[len(map) - 1][0] = '#'
    map[len(map) - 1][len(map[0]) - 1] = '#'
    return map

if __name__ == "__main__":
    content = [list(row) for row in get_file_content(DATA_PATH).split("\n") if row]
    print(f"Part 1: {GameOfLife(content, 100)}")
    print(f"Part 2: {GameOfLife(content, 100, turnCornerOn)}")
