#!/usr/bin/python3

def forward(str):
    new_str = ""
    i = 0
    while i < len(str):
        counter = 0
        number = str[i]
        while i < len(str) and str[i] == number:
            counter += 1
            i += 1
        new_str += f"{counter}{number}"
    return new_str


def lookAndSay(number):
    start_point = "1113122113"
    for _ in range(number):
        start_point = forward(start_point)
    return len(start_point)


if __name__ == "__main__":
    print(f"Part 1: {lookAndSay(40)}")
    print(f"Part 2: {lookAndSay(50)}")
