#!/usr/bin/python3

DATA_PATH = "./data/2015/day_20.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def part_1(desiredPresents):
    max_house = int(desiredPresents / 10)
    houses = [0] * max_house

    for elf_num in range(1, max_house):
        for house_num in range(elf_num, max_house, elf_num):
            houses[house_num] += elf_num * 10
    for i in range(1, max_house):
        if houses[i] >= desiredPresents:
            return i
    return None


def part_2(desiredPresents):
    max_house = int(desiredPresents / 10)
    houses = [0] * max_house

    for elf_num in range(1, max_house):
        visited = 0
        for house_num in range(elf_num, max_house, elf_num):
            houses[house_num] += elf_num * 11
            visited += 1
            if visited >= 50:
                break

    for i in range(1, max_house):
        if houses[i] >= desiredPresents:
            return i
    return None

if __name__ == "__main__":
    desiredPresents = int(get_file_content(DATA_PATH))
    print(f"Part 1: {part_1(desiredPresents)}")
    print(f"Part 2: {part_2(desiredPresents)}")
