#!/usr/bin/python3

DATA_PATH = "./data/2025/day_04.txt"

def get_file_content(filepath):
    with open(filepath, 'r') as file:
        return file.read()

def areTooMuchBoxNear(content, i, j):
    count = 0
    for x in range(-1, 2):
        for y in range(-1, 2):
            if (x == 0 and y == 0) or i + x < 0 or i + x >= len(content) or j + y < 0 or j + y >= len(content[0]):
                continue
            if content[i + x][j + y] == "@":
                count += 1
    return count >= 4

def part_1(content):
    counter = 0
    for i in range(len(content)):
        for j in range(len(content[0])):
            if content[i][j] == "@":
                if not areTooMuchBoxNear(content, i, j):
                    counter += 1
    return counter

def part_2(content):
    counter = 0
    content = [list(row) for row in content]
    dup_content = content.copy()
    flag = True
    while flag:
        content = dup_content.copy()
        flag = False
        for i in range(len(content)):
            for j in range(len(content[0])):
                if content[i][j] == "@":
                    if not areTooMuchBoxNear(content, i, j):
                        counter += 1
                        dup_content[i][j] = "."
                        flag = True
    return counter

if __name__ == "__main__":
    content = get_file_content(DATA_PATH)
    content = [row for row in content.split("\n") if row]
    print(f"Part 1: {part_1(content)}")
    print(f"Part 2: {part_2(content)}")
